baseURL = "http://sund.site/"
languageCode = "zh-cn"
title = "電波障害"
theme = "ghostwriter"
copyright = "Steve Sun"
googleAnalytics = "UA-64688885-1"
disqusShortname = "v2steve"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Steve Sun"

[Params]
    mainSections = ["posts"]
    intro = true
    twitter = "https://twitter.com/way2steve"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "2006-01-02"
    readingTime = true
    readingTimeText = "Estimated reading time:"
