baseURL = "https://sund.site/"
title = "Steve Sun"

# disqusShortname = 'v2steve'       # use disqus comments

[params]
# color style
color = 'linen' # linen, wheat, gray, light

# header social icons
twitter = 'way2steve' # twitter.com/YOUR_TWITTER_ID
github = 'stevedsun'  # github.com/YOUR_GITHUB_ID
# instagram = 'YOUR_INSTAGRAM_ID' # instagram.com/YOUR_INSTAGRAM_ID
# linkedin = 'YOUR_LINKEDIN_ID'   # linkedin.com/in/YOUR_LINKEDIN_ID
# mastodon = 'YOUR_MASTODON_LINK' # e.g. 'https://mastodon.instance/@xxx'
rss = true # show rss icon

# home page profile
# avatar = '/android-chrome-192x192.png' # gravatar email or image url
# name = 'Steve Sun'
# bio = 'A garden of mindset.'


# misc
# disableHLJS = true                       # disable highlight.js
# disablePostNavigation = true             # disable post navigation
monoDarkIcon = true # show monochrome dark mode icon
# gravatarCdn = 'GRAVATAR_CDN_LINK'        # e.g. 'https://cdn.v2ex.com/gravatar/'
# graphCommentId = "YOUR_GRAPH_COMMENT_ID" # use graph comment (disqus alternative)
# math = true # enable KaTeX math typesetting globally

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"
[[module.imports]]
path = 'github.com/hugomods/google-analytics'
# [[module.imports]]
# path = 'github.com/hugomods/images'
