baseURL = "https://sund.site/"
languageCode = "en"
defaultContentLanguage = "en"
title = "電波障害"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 40
paginate = 10                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = "UA-64688885-1"                   # your google analytics id
disqusShortname = "v2steve"                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                     # 必需
  name = "Steve Sun"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "Steve Sun, a full-stack developer"                                       # site's subTitle  # 网站二级标题
  footerSlogan = ""                                   # site's footer slogan  # 网站页脚标语
  keywords = ["Steve Sun","Notion","Develop", "Programm", "Coding", "Note-taking", "Book"]                                  # site's keywords  # 网站关键字
  description = "Steve Sun's blog"                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = false                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
  github = "https://github.com/stevedsun"
  twitter = "https://twitter.com/way2steve"
  facebook = ""
  weibo = ""
  instagram = ""

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
