baseURL = "https://sund.site"
title = "电波障害"
author = "Steve Sun"
copyright = "© 2021, Steve Sun"
paginate = 4
languageCode = "zh"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "offline"

[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  description = "An engineer's blog"
  featured = true
  cssonly = false

  [params.socials]
    twitter = "https://twitter.com/way2steve"
    github = "https://github.com/stevedsun"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

