# Site settings
baseurl = "http://sund.site"
languageCode = "en-us"
title = "電波障害"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-64688885-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "v2steve"

[params]
	name = "Steve Sun"
	description = "Blog of Steve Sun"
	bio = "Programmer, Ricoh GR II User"
	# Enter optionally your twitter account
	twitter = "https://twitter.com/way2steve"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "微信公众号: 電波障害"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://twitter.com/way2steve"
    github   = "https://www.github.com/sundiontheway"
    instagram = "https://www.instagram.com/_steve_sun_/?hl=zh-cn"
    rss = "https://sund.site/index.xml"
