baseURL = "https://sund.site/"
title = "電波障害"

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"

[params]
# color style
color = 'linen' # linen, wheat, gray, light

# header social icons
twitter = 'way2steve'   # twitter.com/YOUR_TWITTER_ID
github = 'stevedsun'    # github.com/YOUR_GITHUB_ID
instagram = 'stevedsun' # instagram.com/YOUR_INSTAGRAM_ID
# linkedin = 'YOUR_LINKEDIN_ID'   # linkedin.com/in/YOUR_LINKEDIN_ID
# mastodon = 'YOUR_MASTODON_LINK' # e.g. 'https://mastodon.instance/@xxx'
rss = true # show rss icon

# home page profile
avatar = '/android-chrome-192x192.png' # gravatar email or image url
name = 'Steve Sun'
bio = 'I make softwares.'


# misc
# disableHLJS = true                       # disable highlight.js
# disablePostNavigation = true             # disable post navigation
# monoDarkIcon = true # show monochrome dark mode icon
# gravatarCdn = 'GRAVATAR_CDN_LINK'        # e.g. 'https://cdn.v2ex.com/gravatar/'
graphCommentId = "steve-sun" # use graph comment (disqus alternative)
# math = true # enable KaTeX math typesetting globally

[services]
[services.googleAnalytics]
ID = 'G-XJJVVQ0LBH'

[taxonomies]
tag = "tags"
category = "categories"

[menu]
[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20
